config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to:"homes#top"
  resources :post_images
  resources :users, only: [:show, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post_image.rb
class PostImage < ApplicationRecord

  belongs_to :user
  # ユーザーとのアソシエーション、1:N
  attachment :image
  # この場合、imageに_idは含めない
  # モデルに、画像アップ用のメソッド（attachment）を追加してフィールド名に（image）を指定

  validates :photo_name, presence: true
  validates :image, presence: true
  # photonameとimageカラムに空白禁止のバリデーションを指定

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_images, dependent: :destroy
  # 画像投稿とのアソシエーション、　１：N

  attachment :profile_image
  # モデルに、画像アップ用のメソッド（attachment）を追加してフィールド名に（profile_image）を指定
  
  validates :name, presence: true
  # nameカラムに空白禁止のバリデーションを指定

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

   before_action :authenticate_user!,except: [:top]
  # ログイン認証が成功していないと、トップページ以外の画面（ログインと新規登録は除く）は表示できない仕様

  before_action :configure_permitted_parameters, if: :devise_controller?
  # devise利用の機能（ユーザ登録、ログイン認証など）が使われる場合、その前にconfigure_permitted_parametersが実行

  def after_sign_in_path_for(resource)
    post_images_path
  end
  # ログイン後は投稿一覧画面に遷移

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  # configure_permitted_parametersでは、devise_parameter_sanitizer.permitでnameのデータ操作を許可するアクションメソッドが指定
  # 今回のケースでは、ユーザ登録（sign_up）の際に、ユーザ名（name）のデータ操作が許可

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end
  
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController

  def new
    @post_image = PostImage.new
  end

  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    if @post_image.save
      redirect_to post_images_path
    else
      render :new
    end
    
  end

  def index
    @post_images = PostImage.page(params[:page]).per(3)
  end

  def show
    @post_image = PostImage.find(params[:id])
  end

  def destroy
    @post_image = PostImage.find(params[:id])
    @post_image.destroy
    redirect_to post_images_path
  end

  def edit
    @post_image = PostImage.find(params[:id])
  end

  def update
    @post_image = PostImage.find(params[:id])
    if @post_image.update(post_image_params)
      redirect_to post_images_path
    else
      render :edit
    end
    
  end

  private

  def post_image_params
    params.require(:post_image).permit(:photo_name, :image, :caption)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    @post_images = @user.post_images.page(params[:page]).per(3)
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id) 
    else
      render :edit
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<div class="container py-5">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-camera-retro"></i><strong>Photoryes</strong>  !!</h1>
      <p>In  <i class="fas fa-camera-retro"></i><strong>Photoryes</strong>, </p>
      <p>Leave your memoryes on your photos</p>
      <div class="btn-wrapper col-10 mx-auto py-3">
        <div class="row">
          <%= link_to 'Log in',new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to 'Sign Up',new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_errors.html.erb
<!--<= render 'layout/errors' , obj: @~~ %> -->

<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class = 'container mt-5'>
    <div class = 'row'>
      <div class = 'mx-auto'>
        <p><i class="fas fa-camera-retro"></i> Photoryes 写真と共に思い出を残そう</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <!--画面幅に応じて、バー・アイコンを切り替えて表示-->
      <div class="container">
        <a class="navbar-brand p-3" href="/"><span>Photoryes</span></a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <!--ハンバーガーメニューを表示-->
        <!--data-toggle="collapse"、data-target="#[id名]"は必ず指定、アイコンの開閉(折りたたみ）に関わる-->

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <!--collapseで折りたたみをする、navbarのclass・idを指定-->
          <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'マイページ', user_path(current_user.id), class: ' nav-link text-light' %>
          </li>
          <li class="nav-item">
            <%= link_to '投稿フォーム', new_post_image_path, class: ' nav-link text-light' %>
          </li>
          <li>
            <%= link_to '投稿一覧', post_images_path, class: ' nav-link text-light' %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: ' nav-link text-light' %>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-light' %>
          </li>
          <li class="nav-item">
            <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-light' %>
          </li>
          <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photoryes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <!--headerの部分テンプレート呼び出し-->
    <main class = "mb-auto">
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
    <!--footerの部分テンプレート呼び出し-->
  </body>
</html>

app/views/post_images/_form.html.erb
<%= form_with model: post_image, local:true do |f| %>
  <%= f.attachment_field :image, class: "w-100" %>
  <div class="input-group mb-3 mt-4">
    <div class="input-group-prepend">
    <!--prepend付与するclass名-->
      <span class="input-group-text" aria-hidden="true"><i class="fas fa-heading"></i></span>
    </div>
    <%= f.text_field :photo_name, class:"form-control", placeholder:"投稿タイトル" %>
  </div>
  <%= f.text_area :caption, class:"form-control", rows:"5", placeholder:"コメントここに" %>
  <hr>
  <%= f.submit '投稿', class:"btn btn-lg btn-block btn-info mt-4" %>
<% end %>

app/views/post_images/_list.html.erb
<div class="card-list-container py-5">
  <% post_images.each do |post_image| %>
  <div class="card w-50 mx-auto  my-5 shadow-lg">
    <%= link_to post_image_path(post_image.id) do %>
      <%= attachment_image_tag post_image, :image, :fill, 450, 300, class:"card-img-top"; %>
    <% end %>
    <div class="card-body">
      <div class="row">
        <div class="col-2">
          <%= attachment_image_tag post_image.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class:"mt-3 rounded-circle"; %>
        </div>
        <div class="col-10">
          <p class="card-title">
            <%= link_to(post_image_path(post_image.id), class:"text-dark") do %>
              <strong><i class="far fa-flag"></i><span> <%= post_image.photo_name %></span></strong>
            <% end %>
          </p>
          <p class="card-text">
            説明：<%= post_image.caption %>
          </p>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  <%= paginate post_images %>
</div>

app/views/post_images/edit.html.erb
<div class="container">
  <div class="row no-gutters">
  <!--.no-gutters を指定すると、カラムのガーター(左右のパディング)を無くす-->
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
    <!--画面幅によって、フォームのサイズを変更-->
      <h5 class="text-light bg-secondary p-4 mb-0">画像投稿編集フォーム</h5>
      <div class="form-body p-4">
        <%= render 'layouts/errors' , obj: @post_image %>
        <%= render 'form', post_image: @post_image %>
      </div>
    </div>
  </div>
</div>

app/views/post_images/index.html.erb
<%= render 'list', post_images: @post_images %>
<!--画像投稿一覧リストの部分テンプレート-->

app/views/post_images/new.html.erb
<div class="container">
  <div class="row no-gutters">
  <!--.no-gutters を指定すると、カラムのガーター(左右のパディング)を無くす-->
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
    <!--画面幅によって、フォームのサイズを変更-->
      <h5 class="text-light bg-secondary p-4 mb-0">画像投稿フォーム</h5>
      <div class="form-body p-4">
        <%= render 'layouts/errors' , obj: @post_image %>
        <%= render 'form', post_image: @post_image %>
      </div>
    </div>
  </div>
</div>

app/views/post_images/show.html.erb
<div class="card-list-container py-5">
  <div class="card w-50 mx-auto mt-4 shadow-lg">
    <%= link_to post_image_path(@post_image.id) do %>
      <%= attachment_image_tag @post_image, :image, :fill, 450, 300, class:"card-img-top"; %>
    <% end %>
    <div class="card-body">
      <div class="row">
        <div class="col-2">
          <%= attachment_image_tag @post_image.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class:"mt-3 rounded-circle"; %>
        </div>
        <div class="col-10">
          <p class="card-title">
            <%= link_to(post_image_path(@post_image.id), class:"text-dark") do %>
              <strong><i class="far fa-flag"></i><span> <%= @post_image.photo_name %></span></strong>
            <% end %>
          </p>
          <p class="card-text">説明：<%= @post_image.caption %></p>
          <p>投稿日時：<%= @post_image.created_at.strftime('%Y/%m/%d') %></p>
          <% if @post_image.user == current_user %>
            <%= link_to "削除", post_image_path(@post_image), method: :delete, data: { confirm: '本当に削除しますか？' } %>
            |
            <%= link_to "編集", edit_post_image_path(@post_image) %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row no-gutters">
  <!--.no-gutters を指定すると、カラムのガーター(左右のパディング)を無くす-->
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
    <!--画面幅によって、フォームのサイズを変更-->
      <h5 class="text-light bg-secondary p-4 mb-0">会員情報編集フォーム</h5>
      <div class="form-body p-4">
        <%= render 'layouts/errors' , obj: @user %>
        <%= form_with model: @user, local:true do |f| %>
          <%= f.attachment_field :profile_image, class: "w-100" %>
          <div class="input-group mb-3 mt-4">
            <div class="input-group-prepend">
            <!--prepend付与するclass名-->
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-user"></i></span>
            </div>
            <%= f.text_field :name, class:"form-control" %>
          </div>
          <hr>
          <%= f.submit '投稿', class:"btn btn-lg btn-block btn-info mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="card-list-container py-5">
  <div class="card  mx-auto shadow-lg" style="max-width: 500px;">
    <div class="row no-gutters">
      <div class="col-6">
        <%= attachment_image_tag @user, :profile_image, :fill, 200, 200, fallback: "no_image.jpg" %>
      </div>
      <div class="col-6">
        <div class="card-body">
          <h3 class="card-title">
            <%= @user.name %>
          </h3>
          <p class="card-text">
            <% if @user.id == current_user.id %>
              <p><%= link_to "プロフィール編集", edit_user_path(@user), class: "btn btn-success" %></p>
            <% end %>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render 'post_images/list', post_images: @post_images %>
<!--画像投稿一覧リストの部分テンプレート-->